# Build Stage
FROM ubuntu:24.04 AS builder

RUN apt-get update && apt-get install -y g++ cmake libasio-dev

COPY . /app
WORKDIR /app

RUN g++ -O3 src/aivora_core/main.cpp -lpthread -o aivora_core

# Runtime Stage
FROM ubuntu:24.04

RUN apt-get update && apt-get install -y curl
COPY --from=builder /app/aivora_core /usr/local/bin/aivora_core

EXPOSE 8080
CMD ["aivora_core"]
